[GENERAL]

#  Unlocks camera rotation so you can look around in any direction.
bUnlockCamera = true

#  Turns the camera with the mouse instead of by moving the cursor to the edge of the screen.
#  This setting implies bUnlockCamera is enabled.
bFreeLook = false

#  Stops the camera from turning to face the speaker when you start a conversation.
bDisableTurnToSpeakerPlayerInitiated = false

#  Stops the camera from turning to face the speaker when an NPC starts a conversation with you.
#  Not recommended, as you may not be able to tell who is talking to you.
bDisableTurnToSpeakerNPCInitiated = false


[CONTROLS_KEYBOARD]
bAllowMovement = true
bAllowRun = true
bAllowToggleRun = true
bAllowJump = false
bAllowSprint = false
bAllowTogglePOV = false
bAllowSneak = false
bAllowReadyWeapon = false
bAllowLeftAttack = false
bAllowRightAttack = false
bAllowHotkeys = false
bAllowShout = false


[CONTROLS_CONTROLLER]
bAllowMovement = true
bAllowRun = true
bAllowToggleRun = true
bAllowJump = false
bAllowSprint = false
bAllowTogglePOV = false
bAllowSneak = false
bAllowReadyWeapon = false
bAllowLeftAttack = false
bAllowRightAttack = false
bAllowHotkeys = false
bAllowShout = false


[AUTOCLOSE]

#  Enable or disable auto-closing of the dialogue menu if the distance to the speaker is too large.
bAutoCloseMenus = true

#  The maximum distance (in in-game units) before the menu will automatically close.
#  Too small values can cause the menus to close immediately.
fAutoCloseDistance = 1350.000000

#  The maximum distance (in in-game units) where the menu NEVER auto-closes (in relation to the players initial position when the menu was opened).
#  This is used as a failsafe when the initial distance is larger than the maximum allowed to prevent the menu from closing immediately.
fAutoCloseTolerance = 400.000000
