#ifndef DME_VERSION_INCLUDED
#define DME_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define DME_VERSION_MAJOR 2
#define DME_VERSION_MINOR 0
#define DME_VERSION_PATCH 0
#define DME_VERSION_BETA 0
#define DME_VERSION_VERSTRING   \
	MAKE_STR(DME_VERSION_MAJOR) \
	"." MAKE_STR(DME_VERSION_MINOR) "." MAKE_STR(DME_VERSION_PATCH) "." MAKE_STR(DME_VERSION_BETA)

#endif
