set(SOURCES
	include/AutoCloseManager.h
	include/Hooks.h
	include/ModConfigUI.h
	include/PCH.h
	include/Settings.h
	src/AutoCloseManager.cpp
	src/Hooks.cpp
	src/ModConfigUI.cpp
	src/Settings.cpp
	src/main.cpp
)
